apiVersion: v1
kind: Service
metadata:
  name: product-recommendation-service
spec:
  selector:
    app: product-recommendation-service-deployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer