apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-recommendation-service-deployment
  labels:
    app: product-recommendation-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-recommendation-service
  template:
    metadata:
      labels:
        app: product-recommendation-service
    spec:
      containers:
      - name: product-recommendation-service
        image: benjaminsh/blue_cart_product_recommendation_service:latest
        ports:
        - containerPort: 3000