apiVersion: v1
kind: Service
metadata:
  name: product-shopping-cart-service
spec:
  selector:
    app: product-shopping-cart-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: NodePort