apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-shipping-service-deployment
  labels:
    app: product-shipping-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-shipping-service
  template:
    metadata:
      labels:
        app: product-shipping-service
    spec:
      containers:
      - name: product-shipping-service
        image: benjaminsh/blue_cart_product_shipping_service:latest
        ports:
        - containerPort: 3000
        env:
          - name: MYSQL_DB_HOST
            valueFrom:
              secretkeyRef:
                name: bluecartsecrets
                key:  MYSQL_DB_HOST
          - name: MYSQL_DB_USERNAME
            valueFrom:
              secretkeyRef:
                name: bluecartsecrets
                key:  MYSQL_DB_USERNAME
          - name: MYSQL_DB_PASSWORD
            valueFrom:
              secretkeyRef:
                name: bluecartsecrets
                key:  MYSQL_DB_PASSWORD