apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-review-service-deployment
  labels:
    app: product-review-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-review-service
  template:
    metadata:
      labels:
        app: product-review-service
    spec:
      containers:
      - name: product-review-service
        image: benjaminsh/blue_cart_product_review_service:latest
        ports:
        - containerPort: 3000
        env:
          - name: MONGO_DB_USERNAME
            valueFrom:
              secretkeyRef:
                name: bluecartsecrets
                key:  MONGO_DB_USERNAME
          - name: MONGO_DB_USERNAME
            valueFrom:
              secretkeyRef:
                name: bluecartsecrets
                key:  MONGO_DB_PASSWORD
          - name: MONGO_DB_PASSWORD
            valueFrom:
              secretkeyRef:
                name: bluecartsecrets
                key:  MONGO_DB_CLUSTER_ADDRESS