apiVersion: v1
kind: Service
metadata:
  name: product-services-gateway
spec:
  selector:
    app: product-services-gateway
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer